Revert "Better logging of compile errors"
This reverts commit 1b328ad0def64f2f339d0aa705a923034e7d4086.

I'm not sure if such error message could contain sensitive information
(like: NoMethodError: undefined method 'foobarbaz' for
"SECURE SECRET='this is secret'")

Reverting for now.